### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by TCROC** [StardustDL/Linq-in-Rust#6]
I'm coming from C# to Rust and am very intrigued by a LINQ like query library in Rust.  This looks extremely appealing!  Is it still under active development?

**Comment by StardustDL** [comment]
Thanks for your interest! I'm also a C# developer and really like LINQ. That's why I wrote this library. I want to keep this library maintained but I'm busy writing other projects in the past few months since my work.
In the next two months (July and then) I have some free time and want to update this library. It may take time since I'm a C#&Rust fan but not an expert.

**Comment by TCROC** [comment]
Awesome!  If I get some free time, maybe I'll contribute some things!  I'm glad to hear that its still maintained!
